INSERT INTO alerts (title, description, type, latitude, longitude, user_id, created_at, updated_at, severity, status)
VALUES
    ('Suspicious Activity in Luxembourg City',
     'A suspicious vehicle was spotted near the train station. Authorities are investigating.',
     'CRIME',
     49.6117,
     6.13,
     1,
     NOW(),
     NOW(),
     'LOW',
     'ACTIVE'),

    ('Crime Reported at Gare',
     'A robbery took place at the main train station. Police are investigating the incident.',
     'CRIME',
     49.6117,
     6.13,
     2,
     NOW(),
     NOW(),
     'MEDIUM',
     'ACTIVE'),

    ('Flooding in Esch-sur-Alzette',
     'Heavy rainfall caused flooding in the Esch-sur-Alzette area, emergency services are on-site.',
     'HAZARD',
     49.4977,
     5.9800,
     3,
     NOW(),
     NOW(),
     'HIGH',
     'ACTIVE'),

    ('Emergency Medical Alert at Clervaux',
     'A medical emergency occurred near Clervaux, paramedics are en route to assist.',
     'EMERGENCY',
     49.8786,
     6.0347,
     1,
     NOW(),
     NOW(),
     'HIGH',
     'ACTIVE');